spring:
  profiles:
    active: login
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xbshop?characterEncoding=utf8&serverTimezone=Hongkong
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#  resources:
#    static-locations: classpath:/,classpath:/HTML/
  redis:
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com:
      lyh:
        xiaobiao:
          mapper: trace
    org:
      springframework:
        cache: trace
server:
  servlet:
    context-path: /xbiaoshop
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
#    object-wrapper-factory: com.lyh.xiaobiao.util.MapWrapperFactory

kaptcha:
  height: 34
  width: 80
  content:
    length: 4
    source: 1234567890
    space: 2
  font:
    color: black
    size: 30
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1
xbiaoshop:
  uploads-file: D:\nginx-1.16.1\html\uploads\
  uploads-url: http://localhost/uploads/
ftp:
  port: 21
  username: user
  password: user

